-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Forum_Group CASCADE;
DROP TABLE IF EXISTS Forum_User CASCADE;
DROP TABLE IF EXISTS Group_Member CASCADE;
DROP TABLE IF EXISTS Topic CASCADE;
DROP TABLE IF EXISTS Forum_Message CASCADE;
DROP TABLE IF EXISTS Has_Read CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Tagged CASCADE;


